### ISSUE TITLE
Error seen which activating Paytm plugin in Wordpress 5.7.1

### ISSUE THREAD

**Issue by vidhusri** [paytm/Paytm_Wordpress_Plugin#1]
Hello,

We are trying to integrate Paytm plugin to our wordpress site.
I have followed instructions mentioned in https://developer.paytm.com/docs/wordpress/
Downloaded the latest paytm plugin and installed in our wordpress site (version 5.7.1). While activating saw the below error

Warning: Undefined array key "value" in C:\xampp\htdocs\bhuvaneshwariamman\wordpress\wp-content\plugins\paytm-donation\paytm-donation.php on line 295

and
"The plugin generated 1764 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin

Could you please let us know how to fix these errors?
As we are going to use paytm plugin to our wordpress site, would be good to receive response from you at the earliest.

THanks
Vidhya

**Comment by abpaytm** [comment]
Hi, 
Please mail your detailed concern on cmt.ops@paytm.com
