### ISSUE TITLE
Notice: Undefined index: value in /var/www/html/wp-content/plugins/paytm-donation/paytm-donation.php on line 304

### ISSUE THREAD

**Issue by mr-engin3er** [paytm/Paytm_Wordpress_Plugin#2]
After copy paytm-dontion folder in plugins directory, I activated the plugin and it is giving me the error

> Notice: Undefined index: value in /var/www/html/wp-content/plugins/paytm-donation/paytm-donation.php on line 304
> 
> Notice: Undefined index: value in /var/www/html/wp-content/plugins/paytm-donation/paytm-donation.php on line 304
> 
> Notice: Undefined index: value in /var/www/html/wp-content/plugins/paytm-donation/paytm-donation.php on line 304

OS:- AWS Linux 2 inside EC2
PHP Version 7.2.34 
cURL Version 7.61.1
Wordpress Version 5.8.1

**Comment by rahul2bisht** [comment]
We have fixed this issue.
